Repository cloudfoundry/bosh, pull requests merged in 2019-03, with the labels that each got.

#2147 Speedup performance of job template rendering
  src/bosh-director-core/lib/bosh/director/core/templates/job_template_renderer.rb
  src/bosh-template/lib/bosh/template/evaluation_context.rb
Labels: scheduled

#2152 Add unit tests for EvaluationContext.== operator
  src/bosh-template/lib/bosh/template/evaluation_context.rb
  src/bosh-template/spec/unit/bosh/template/evaluation_context_spec.rb
Labels: unscheduled

#2144 Scan and fix request containing all missing VMs of deployment, resurrect VMs in parallel
  src/bosh-director/lib/bosh/director/problem_resolver.rb
  src/bosh-director/spec/unit/problem_resolver_spec.rb
  src/bosh-monitor/lib/bosh/monitor/events/alert.rb
  src/bosh-monitor/lib/bosh/monitor/instance_manager.rb
  src/bosh-monitor/lib/bosh/monitor/plugins/resurrector.rb
  src/bosh-monitor/lib/bosh/monitor/plugins/resurrector_helper.rb
  src/bosh-monitor/spec/unit/bosh/monitor/instance_manager_spec.rb
  src/bosh-monitor/spec/unit/bosh/monitor/plugins/resurrector_helper_spec.rb
  src/bosh-monitor/spec/unit/bosh/monitor/plugins/resurrector_spec.rb
Labels: in progress

#2140 Update BOSH cck for CPI API V2 and mount the disk in case of reboot option
  src/bosh-director/lib/bosh/director/problem_handlers/mount_info_mismatch.rb
  src/bosh-director/spec/unit/problem_handlers/mount_info_mismatch_spec.rb
Labels: in progress

#2146 Reattach persistent disk if mismatch
  src/bosh-director/lib/bosh/director/disk_manager.rb
  src/bosh-director/spec/unit/disk_manager_spec.rb
Labels: in progress
